name: Prepare next release ğŸš€

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Run release draft to extract labels â˜•ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Run release draft to extract labels â˜•ï¸
        uses: tchoupinax/repo-config/shared-actions/dx/prepare-draft-release@db89e9d50f7a2f66da683a659213997894ff2155
        with:
          appId: ${{ secrets.DEPLOY_APP_ID }}
          privateKey: ${{ secrets.DEPLOY_APP_KEY }}
